package_configurations:
  - id: "Maven:io.arrow-kt:arrow-core:1.1.3"
    source_artifact_url: "https://repo1.maven.org/maven2/io/arrow-kt/arrow-core/1.1.3/arrow-core-1.1.3-sources.jar"
    path_excludes:
      - pattern: "docs/**"
        reason: "DOCUMENTATION_OF"
        comment: "This directory contains documentation which is not distributed."
  - id: "Maven:io.arrow-kt:arrow-core:1.1.3"
    source_artifact_url: "https://repo1.maven.org/maven2/io/arrow-kt/arrow-core/1.1.3/arrow-core-1.1.3-sources.jar"
    path_excludes:
      - pattern: "docs_duplicate/**"
        reason: "DOCUMENTATION_OF"
        comment: "This directory contains documentation which is not distributed."